#!/bin/bash

active="$(xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME | sed -E -e 's/^.{28}//;s/[^A-Za-z0-9]//g')"
timestamp=$(date +%Y%m%d-%s)
fpath="$HOME/Pictures/Screenshots/${active}-${timestamp}.png"
scrot "${fpath}"
notify-send "Screenshot captured" "${fpath}"
