#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x34"
font="PermanentMarker-8:style=Regular"
#font="ArchivoNarrow-10:style=Bold"
#font="NotoSans-10"
#font="Roboto-9:style=Bold"
iconfont="FontAwesome-11"
res_w=$(xrandr | grep "current" | awk '{print $8a}')

# Alarm settings
cpu_alert=20                        # % cpu use
net_alert=5                         # K net use

# update setting, in seconds (conky update in i3_lemonbar_conky
upd_vol=3                           # Volume update
upd_mail=300                        # Mail check update
upd_mpd=5                           # MPD song update
upd_bat=5                           # Battey update
upd_ssid=30                         # SSID update

# --- APPLY XRES BEGIN
c_red_l="#fffb4934"
c_blue_l="#ff83a598"
c_blue_d="#ff458588"
c_magenta_d="#ffb16286"
c_black_d="#ff1d2021"
c_cyan_l="#ff8ec07c"
c_magenta_l="#ffd3869b"
c_yellow_l="#fffabd2f"
c_red_d="#ffcc241d"
c_background="#ff282828"
c_cyan_d="#ff689d6a"
c_green_l="#ffb8bb26"
c_foreground="#ffebdbb2"
c_white_d="#ffdbae93"
c_green_d="#ff98971a"
c_yellow_d="#ffd79921"
c_cursor="#fffff000"
c_white_l="#fffbf1c7"
c_black_l="#ff665c54"
# --- APPLY XRES END

# Christmas Colors
# Taken from https://color.adobe.com/Classic-Christmas-color-theme-2868486
holiday_green_d="#ff142715"
holiday_green_l="#ff667432"
holiday_cream="#fff2f0d8"
holiday_red_l="#ffe02526"
holiday_red_d="#ffa11d21"

# Colors

# General Colors
color_back="$holiday_cream"
color_fore="$holiday_green_d"
color_normalbg="$color_back"
color_normalfg="$color_fore"
color_normalul="$color_back"

# Colors for muted elements
color_mutedbg="$color_back"
color_mutedfg="$c_black_l"

# Colors for unselected workspaces
color_uwspbg="$holiday_red_d"
color_uwspfg="$holiday_red_l"

# Colors for selected workspace
color_wspbg="$color_uwspbg"
color_wspul="$color_wspbg"
color_wspfg="$holiday_cream"

# Colors for clock area
color_clockbg="$holiday_green_l"
color_clockul="$color_clockbg"
color_clockfg="$holiday_cream"

# Colors for battery monitor
color_success="$holiday_green_l"
color_successbg="$color_back"
color_successul="$holiday_green_l"
color_successfg="$color_fore"

color_warning="$c_yellow_l"
color_warningbg="$color_back"
color_warningul="$c_yellow_l"
color_warningfg="$c_yellow_l"

color_critical="$c_red_l"
color_criticalbg="$c_red_d"
color_criticalul="$c_red_l"
color_criticalfg="$c_white_l"

#default space between sections
stab='    '

# Char glyps for powerline fonts
sep_left=" "                        # Powerline separator left
sep_right=" "                       # Powerline separator right
sep_l_left=" "                      # Powerline light separator left
sep_l_right=" "                     # Powerline light sepatator right

# Icon glyphs from Terminusicons2
# icon_clock="Õ"                      # Clock icon
# icon_cpu="Ï"                        # CPU icon
# icon_mem="Þ"                        # MEM icon
# icon_dl="Ð"                         # Download icon
# icon_ul="Ñ"                         # Upload icon
# icon_vol="Ô"                        # Volume icon
# icon_hd="À"                         # HD / icon
# icon_home="Æ"                       # HD /home icon
# icon_mail="Ó"                       # Mail icon
# icon_chat="Ò"                       # IRC/Chat icon
# icon_music="Î"                      # Music icon
# icon_prog="Â"                       # Window icon
# icon_contact="Á"                    # Contact icon
# icon_wsp="Ç"                        # Workspace icon
# icon_battery=""                    # Battery icon
# icon_charging="+"                   # Charging icon

# Icon glyphs from Siji
# icon_clock=""                      # Clock icon
# icon_cpu=""                        # CPU icon
# icon_mem=""                        # MEM icon
# icon_dl=""                         # Download icon
# icon_ul=""                         # Upload icon
# icon_vol=""                        # Volume icon
# icon_mute=""
# icon_hd="À"                         # HD / icon
# icon_home="Æ"                       # HD /home icon
# icon_mail="Ó"                       # Mail icon
# icon_chat="Ò"                       # IRC/Chat icon
# icon_music=""                      # Music icon
# icon_music_playing=""
# icon_music_paused=""
# icon_prog=""                       # Window icon
# icon_contact="Á"                    # Contact icon
# icon_wsp=""                        # Workspace icon
# icon_battery="         "
# icon_charging=""

# Ionicon glyphs
icon_battery="    "
icon_clock=""                        # Clock icon
icon_calendar=""
icon_cpu=""                          # CPU icon
#icon_globe=""                        # Globe icon
icon_home=""                         # Home icon (also linux)
#icon_laptop=""                       # Laptop icon
icon_linux=""                        # Linux (Tux) icon
icon_mail=""                         # Email icon
#icon_mem="?"                          # Memory icon
icon_music=""                        # Music icon
icon_paw=""                          # Paw icon
icon_prog=""                         # Window icon
icon_shell=""                        # Shell icon
icon_vol=""                          # Volume icon
icon_mute=""
#icon_wsp=""                          # Workspace icon (paw duplicate for now)
icon_charging=""
icon_dl=""
icon_ul=""
icon_ssid=""
